name: Cross-Referencing Pipeline

permissions:
  contents: write

on:
  workflow_dispatch:

jobs:
  run_cross_referencing_pipeline:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
            persist-credentials: true

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Install R packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: fs, gargle, glue, googlesheets4, here, readxl, tidyverse
          cache-version: 1

      - name: Setup Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Run 'generate_templates.qmd' script
        run: quarto render code/generate_templates.qmd
        env:
          GOOGLE_SERVICE_ACCOUNT_JSON: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}

      - name: Run 'generate_crosswalks.qmd' script
        run: quarto render code/generate_crosswalks.qmd

      #- name: Run 'generate_gee_dictionaries.R' script
      #  run: Rscript code/generate_gee_dictionaries.R

      - name: Commit resources folder
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add resources/
          git diff --cached --quiet || git commit -m "Automatic run of the cross-referencing pipeline"
          git push